-- =============================================================================
-- Migration 0063 — Staff directory for salesperson / appraiser pickers (item 53)
-- =============================================================================

CREATE TABLE IF NOT EXISTS tav.staff_directory (
  id              uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  display_name    text        NOT NULL,
  role            text        NOT NULL
    CHECK (role IN ('salesperson', 'appraiser', 'both')),
  is_active       boolean     NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  deactivated_at  timestamptz,
  CONSTRAINT staff_directory_display_name_role_unique UNIQUE (display_name, role)
);

CREATE INDEX IF NOT EXISTS staff_directory_active_role_idx
  ON tav.staff_directory (role, display_name)
  WHERE is_active = true;

CREATE TRIGGER staff_directory_set_updated_at
  BEFORE UPDATE ON tav.staff_directory
  FOR EACH ROW EXECUTE FUNCTION tav.set_updated_at();

-- Seed salespeople from buyer-provided roster screenshots (2026-07-10).
INSERT INTO tav.staff_directory (display_name, role) VALUES
  ('Abaid, Fahd', 'salesperson'),
  ('AbdelRaziq, Firas', 'salesperson'),
  ('Acuna, Roberto', 'salesperson'),
  ('Aguado, Christopher', 'salesperson'),
  ('Aguilar, Dariana', 'salesperson'),
  ('Aguilar, michelle', 'salesperson'),
  ('Aguilar, Sergio', 'salesperson'),
  ('Al-Hiyari, Smah', 'salesperson'),
  ('Albanna, Abdu', 'salesperson'),
  ('Albanna, Boyd', 'salesperson'),
  ('Albanna, Issa', 'salesperson'),
  ('Albanna, Louai', 'salesperson'),
  ('Albanna, Mussa', 'salesperson'),
  ('Albanna, Rami', 'salesperson'),
  ('Albanna, RJ', 'salesperson'),
  ('Albanna, Shireen', 'salesperson'),
  ('Albanna, Yazan', 'salesperson'),
  ('Albanna, Yesmeen', 'salesperson'),
  ('Ali, Urooj', 'salesperson'),
  ('Allen, Chris', 'salesperson'),
  ('Allen, Christopher', 'salesperson'),
  ('Almahayni, Dana', 'salesperson'),
  ('Almahayni, Ranem', 'salesperson'),
  ('ALMAHAYNI, SARAH', 'salesperson'),
  ('Amreya, Motaz', 'salesperson'),
  ('Arif, Asra', 'salesperson'),
  ('Arriaga, Juan', 'salesperson'),
  ('Arutunian, Susan', 'salesperson'),
  ('Ayala, Nicholas', 'salesperson'),
  ('Balak, Brandon', 'salesperson'),
  ('Barnes, Blake', 'salesperson'),
  ('Bataineh, Adam', 'salesperson'),
  ('Bataineh, Anmar', 'salesperson'),
  ('Bays, Nicholas', 'salesperson'),
  ('Bell, Steven', 'salesperson'),
  ('Benjamin, Jason', 'salesperson'),
  ('Bernal, Alexandria', 'salesperson'),
  ('Brown, Jamel', 'salesperson'),
  ('Brown, Kaleb', 'salesperson'),
  ('Bryant, Charlie', 'salesperson'),
  ('Campos, Ermando', 'salesperson'),
  ('Cancelmi, Aidan', 'salesperson'),
  ('Carreon, David', 'salesperson'),
  ('Carreon, Ruben', 'salesperson'),
  ('Cerda, Ivan', 'salesperson'),
  ('Collins, Cameron', 'salesperson'),
  ('Dadar, Niema', 'salesperson'),
  ('Danish, Ibtehaj', 'salesperson'),
  ('Davidson, Tim', 'salesperson'),
  ('Delgado, Alex', 'salesperson'),
  ('Demoe, Sebastian', 'salesperson'),
  ('Dhakhwa, Paras', 'salesperson'),
  ('Diaz, Marisa', 'salesperson'),
  ('Dixon, Japheth', 'salesperson'),
  ('Durbin, Daniel', 'salesperson'),
  ('Edwards, Tyree', 'salesperson'),
  ('Frazier, Colin', 'salesperson'),
  ('Frezza, Jonathan', 'salesperson'),
  ('Frezza, Nicholas', 'salesperson'),
  ('Frezza, Nick', 'salesperson'),
  ('Frezza, Yvonne', 'salesperson'),
  ('Fuentes, Brandon', 'salesperson'),
  ('Ganaway, Isaiah', 'salesperson'),
  ('Garcia, Alondra', 'salesperson'),
  ('Garcia, Ariana', 'salesperson'),
  ('Garcia, Manny', 'salesperson'),
  ('Garza, Selena', 'salesperson'),
  ('Gomez, Kevin', 'salesperson'),
  ('Granados, Lisnasayra', 'salesperson'),
  ('Grant, Jaeon', 'salesperson'),
  ('Gutierrez, Gustavo', 'salesperson'),
  ('Gutierrez, Karla', 'salesperson'),
  ('Gutierrez, Luis', 'salesperson'),
  ('Gutierrez, Noel', 'salesperson'),
  ('Guzman, Johnathan', 'salesperson'),
  ('Hamedeh, Zade', 'salesperson'),
  ('Hawkins, Ashtynn', 'salesperson'),
  ('Hazel, Andrew', 'salesperson'),
  ('Hernandez, Abel', 'salesperson'),
  ('Hernandez, Ulysses', 'salesperson'),
  ('Hernandez, Uriel', 'salesperson'),
  ('Herrera, Litzy', 'salesperson'),
  ('Hoxha, Fisnik', 'salesperson'),
  ('James, Alexis', 'salesperson'),
  ('Jester, Diana', 'salesperson'),
  ('Jibawi, Zeinab', 'salesperson'),
  ('Johnson, Anthony', 'salesperson'),
  ('Jones, Luther', 'salesperson'),
  ('Khader, Anas', 'salesperson'),
  ('Layland, Logan', 'salesperson'),
  ('Lewis, Marissa', 'salesperson'),
  ('Liqteq, PMO', 'salesperson'),
  ('Lopez, Astrid', 'salesperson'),
  ('Lopez, Erik', 'salesperson'),
  ('Lopez, Kayla', 'salesperson'),
  ('Lopez, Leslie', 'salesperson'),
  ('Luna, Karely', 'salesperson'),
  ('Ly, Nam', 'salesperson'),
  ('Marquez, Luis', 'salesperson'),
  ('Martinez, Abigail', 'salesperson'),
  ('Martinez, Alex', 'salesperson'),
  ('Mata, Juan Diego', 'salesperson'),
  ('Memon, Arina', 'salesperson'),
  ('Memon, Raheel', 'salesperson'),
  ('Mendez, Jayson', 'salesperson'),
  ('Mendoza, Marcos', 'salesperson'),
  ('Mirza, Malik', 'salesperson'),
  ('Modester, Brian', 'salesperson'),
  ('Montgomery, Kent', 'salesperson'),
  ('Mosquea, Myrick', 'salesperson'),
  ('Nixon, Trellis', 'salesperson'),
  ('Noguez, Eva', 'salesperson'),
  ('Noguez, Marissa', 'salesperson'),
  ('Orellan, Jackeline', 'salesperson'),
  ('Orquiz, Toni', 'salesperson'),
  ('Ortiz, Nancy', 'salesperson'),
  ('Oscars, Marlon', 'salesperson'),
  ('Padilla, Jose', 'salesperson'),
  ('Pavliuk, Roman', 'salesperson'),
  ('Pazol, Josh', 'salesperson'),
  ('Pelayo, David', 'salesperson'),
  ('Peterson, Ryan', 'salesperson'),
  ('Photographer, Tav', 'salesperson'),
  ('Pope, Cody', 'salesperson'),
  ('Porterfield, Karyssa', 'salesperson'),
  ('Portillo, Jailyn', 'salesperson'),
  ('Quintanilla, Alex', 'salesperson'),
  ('Quintanilla, Carlos', 'salesperson'),
  ('Quintero, Pedro', 'salesperson'),
  ('Ralil, Priscilla', 'salesperson'),
  ('Ramirez, Jovanny', 'salesperson'),
  ('Regalado, Madison', 'salesperson'),
  ('Regmi, Rashmi', 'salesperson'),
  ('Reyes Morales, Gabriela', 'salesperson'),
  ('Reyes, Oliver', 'salesperson'),
  ('Reynolds, Luke', 'salesperson'),
  ('Rivera, Danielle', 'salesperson'),
  ('ROBBINS, ZACHARY', 'salesperson'),
  ('Robertoson, Josh', 'salesperson'),
  ('Rodriguez, Alexis', 'salesperson'),
  ('Rodriguez, Fernan', 'salesperson'),
  ('Rodriguez, Paloma', 'salesperson'),
  ('Rojas, Katie', 'salesperson'),
  ('Roman, Jesus', 'salesperson'),
  ('Ropar, Vitalii', 'salesperson'),
  ('Roth, Johnny', 'salesperson'),
  ('Rueda, Alfonso', 'salesperson'),
  ('Salazar, Denisse', 'salesperson'),
  ('Sanchez, Evelyn', 'salesperson'),
  ('Sang, Michelle', 'salesperson'),
  ('Sanichanh, Anthony', 'salesperson'),
  ('Sharp, Tim', 'salesperson'),
  ('Shepard, Santino', 'salesperson'),
  ('Shrestha, Pratik', 'salesperson'),
  ('Siewert, Shane', 'salesperson'),
  ('Smith, Carl', 'salesperson'),
  ('Smith, Juwan', 'salesperson'),
  ('Smith, Taleeia', 'salesperson'),
  ('Stovall, Shaiquon', 'salesperson'),
  ('Tamayo, Roberto', 'salesperson'),
  ('Thomas, Derrick', 'salesperson'),
  ('Thompson, Jenny', 'salesperson'),
  ('Thornton, Derian', 'salesperson'),
  ('Torres, Roselyn', 'salesperson'),
  ('Tran, Sarah', 'salesperson'),
  ('Turner, Stuart', 'salesperson'),
  ('Tyler, Kristopher', 'salesperson'),
  ('Underwood, Jeremy', 'salesperson'),
  ('Vaughan, Sydney', 'salesperson'),
  ('Vega, Cesar', 'salesperson'),
  ('Viguerias, Andy', 'salesperson'),
  ('Viguerias, Jorge', 'salesperson'),
  ('Wamble, Steven', 'salesperson'),
  ('White, Snowy', 'salesperson')
ON CONFLICT (display_name, role) DO NOTHING;
